.class final Lcom/banqu/music/ui/main/MainDataLoader$load$1;
.super Lkotlin/coroutines/jvm/internal/ContinuationImpl;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lcom/banqu/music/ui/main/k;->h(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x18
    name = null
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x3
    }
    d1 = {
        "\u0000\u001a\n\u0000\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000b\n\u0000\n\u0002\u0018\u0002\n\u0002\u0010!\n\u0002\u0018\u0002\u0010\u0000\u001a\u0004\u0018\u00010\u00012\u0006\u0010\u0002\u001a\u00020\u00032\u0016\u0010\u0004\u001a\u0012\u0012\u000e\u0012\u000c\u0012\u0008\u0012\u0006\u0012\u0002\u0008\u00030\u00070\u00060\u0005H\u0086@"
    }
    d2 = {
        "load",
        "",
        "firstLoad",
        "",
        "continuation",
        "Lkotlin/coroutines/Continuation;",
        "",
        "Lcom/banqu/music/ui/base/page/MultiEntry;"
    }
    k = 0x3
    mv = {
        0x1,
        0x1,
        0xf
    }
.end annotation

.annotation runtime Lkotlin/coroutines/jvm/internal/DebugMetadata;
    c = "com.banqu.music.ui.main.MainDataLoader"
    f = "MainDataLoader.kt"
    i = {
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc
    }
    l = {
        0x72,
        0x73,
        0x74,
        0x75,
        0x76,
        0x77,
        0x78,
        0x7a,
        0x7b,
        0x7c,
        0x7d,
        0x7e,
        0x7f
    }
    m = "load"
    n = {
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "recAlbumList",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "recAlbumList",
        "topList",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "recAlbumList",
        "topList",
        "recPlaylistClassify",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "recAlbumList",
        "topList",
        "recPlaylistClassify",
        "searchMore",
        "this",
        "firstLoad",
        "a",
        "bannerResult",
        "websiteResult",
        "recPlaylistResult",
        "liveBroadcastResult",
        "recListSongResult",
        "newSongResult",
        "newAlbumResult",
        "recAlbumListResult",
        "topListResult",
        "recPlaylistClassifyResult",
        "searchMoreResult",
        "normalAdResult",
        "videoAdResult",
        "banner",
        "website",
        "recPlaylist",
        "liveBroadcastList",
        "recListSong",
        "newSong",
        "newAlbum",
        "newSongAlbum",
        "recAlbumList",
        "topList",
        "recPlaylistClassify",
        "searchMore",
        "normalAd"
    }
    s = {
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$22",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$22",
        "L$23",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$22",
        "L$23",
        "L$24",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$22",
        "L$23",
        "L$24",
        "L$25",
        "L$0",
        "Z$0",
        "J$0",
        "L$1",
        "L$2",
        "L$3",
        "L$4",
        "L$5",
        "L$6",
        "L$7",
        "L$8",
        "L$9",
        "L$10",
        "L$11",
        "L$12",
        "L$13",
        "L$14",
        "L$15",
        "L$16",
        "L$17",
        "L$18",
        "L$19",
        "L$20",
        "L$21",
        "L$22",
        "L$23",
        "L$24",
        "L$25",
        "L$26"
    }
.end annotation


# instance fields
.field J$0:J

.field L$0:Ljava/lang/Object;

.field L$1:Ljava/lang/Object;

.field L$10:Ljava/lang/Object;

.field L$11:Ljava/lang/Object;

.field L$12:Ljava/lang/Object;

.field L$13:Ljava/lang/Object;

.field L$14:Ljava/lang/Object;

.field L$15:Ljava/lang/Object;

.field L$16:Ljava/lang/Object;

.field L$17:Ljava/lang/Object;

.field L$18:Ljava/lang/Object;

.field L$19:Ljava/lang/Object;

.field L$2:Ljava/lang/Object;

.field L$20:Ljava/lang/Object;

.field L$21:Ljava/lang/Object;

.field L$22:Ljava/lang/Object;

.field L$23:Ljava/lang/Object;

.field L$24:Ljava/lang/Object;

.field L$25:Ljava/lang/Object;

.field L$26:Ljava/lang/Object;

.field L$3:Ljava/lang/Object;

.field L$4:Ljava/lang/Object;

.field L$5:Ljava/lang/Object;

.field L$6:Ljava/lang/Object;

.field L$7:Ljava/lang/Object;

.field L$8:Ljava/lang/Object;

.field L$9:Ljava/lang/Object;

.field Z$0:Z

.field label:I

.field synthetic result:Ljava/lang/Object;

.field final synthetic this$0:Lcom/banqu/music/ui/main/k;


# direct methods
.method constructor <init>(Lcom/banqu/music/ui/main/k;Lkotlin/coroutines/Continuation;)V
    .locals 0

    iput-object p1, p0, Lcom/banqu/music/ui/main/MainDataLoader$load$1;->this$0:Lcom/banqu/music/ui/main/k;

    invoke-direct {p0, p2}, Lkotlin/coroutines/jvm/internal/ContinuationImpl;-><init>(Lkotlin/coroutines/Continuation;)V

    return-void
.end method


# virtual methods
.method public final invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object;
    .locals 1

    iput-object p1, p0, Lcom/banqu/music/ui/main/MainDataLoader$load$1;->result:Ljava/lang/Object;

    iget p1, p0, Lcom/banqu/music/ui/main/MainDataLoader$load$1;->label:I

    const/high16 v0, -0x80000000

    or-int/2addr p1, v0

    iput p1, p0, Lcom/banqu/music/ui/main/MainDataLoader$load$1;->label:I

    iget-object p1, p0, Lcom/banqu/music/ui/main/MainDataLoader$load$1;->this$0:Lcom/banqu/music/ui/main/k;

    const/4 v0, 0x0

    invoke-virtual {p1, v0, p0}, Lcom/banqu/music/ui/main/k;->h(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;

    move-result-object p1

    return-object p1
.end method
